### ISSUE TITLE
Cannot pass password into server when using NOHUP over SSH

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/brit-service#2]
When SSHing onto the hamburg server and using NOHUP to start the BRIT server it is not connected to the console and no password can be entered.

**Comment by jim618** [comment]
Stackexchange:
http://stackoverflow.com/questions/16619792/how-to-get-password-from-console-when-java-application-is-invoked-using-nohup

**Comment by gary-rowe** [comment]
Was just about to post this. Looking deeper I think we should do the following:

1. Start with `java -jar ...` as usual and note PID
1. Enter credentials at console as usual
1. Send it to background with CTRL+Z
1. Immediately issue `disown -h` to avoid HUP signal based on most recent backgrounded job
1. `exit` from shell and verify continuing operation

One snag we may see is `System.out/err/in` may cause a failure due to the process running as a daemon and having no access to these streams any more.

**Comment by jim618** [comment]
Tried this but the CTRL+Z stops the job. When you exit the session on a Mac it says'
'There are stopped jobs'.
I think if you disown it it's still stopped (not sure).
Anyhow you don't see the /brit/public-key being served.

Also we lose the Java console so would need something like log4j

Will investigate further.

**Comment by jim618** [comment]
I think this works:

1) CRTL+Z   stops the brit-server
2) bg     restarts it in the background
3) exit   ends terminal but doesn't kill the background job

**Comment by gary-rowe** [comment]
That's it. For more details [see this article](http://unix.stackexchange.com/a/148698/19023).

**Comment by jim618** [comment]
Yup and I've redirected the System.out to a log file (brit-server.log) after the password entry so that we keep that.

**Comment by jim618** [comment]
Now the start-brit-server.sh gives the user more feedback on what steps to take:

```
[brit@hamburg142 brit-server]$ ./start-brit-server.sh
Starting BRIT server with PID: 31411
Usage:
1. At the password prompt, enter the password for the matcher secret key ring.
2. Send the BRIT server to background with CTRL+Z
3. Restart the stopped job in the background by typing bg.
4. Exit from shell
5. Verify BRIT server is still running by checking
.. TEST: http://localhost:7070/brit/public-key or
.. LIVE: http://multibit.org/brit/public-key
..
TIP: You can find this process again by typing ps -A | grep brit
Enter password:
Working...
Crypto files OK
Crypto keys OK
Matcher OK
Starting server - output will now go to 'brit-server.log' ...
```

If you try https://multibit.org/brit/public-key you will see the new matcher public key.

Also for compartmentalisation I have created a new user 'brit' that owns the brit-server git project and config files (and nothing else) that runs the dropwizard.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Clearly been working for a while.

Closing.
