### ISSUE TITLE
Update service to use same code structure as other services

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/brit-service#4]
The BRIT service has gotten a little behind the other services in terms of structure and needs a little bit of work to bring it up to the same spec. This issue covers this work.

**Comment by gary-rowe** [comment]
Lots of little fixes all over, but the headline change is the improved health check. This borrows heavily from the functional test in order to call itself and get a `MatcherResponse` which is checked for 50 addresses. It also checks for an accidental use of the test keys.

This is included in the start script as a recommendation after execution to place the emphasis on automated self-test.

Ready for review and close.

**Comment by jim618** [comment]
Looks good - I have updated the startup script (classpath separator, removed "(" in echo as it was causing parsing problems.

@gary-rowe Please make sure the start up script works on your machine, then close.

**Comment by gary-rowe** [comment]
Needed to create Windows variant (classpath uses `;` on Windows) but it works.

Closing.
