### ISSUE TITLE
Produce backups of critical files

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/brit-service#6]
Produce a timestamped zip file of critical files (e.g. wallet ids) for easy consumption for other processes (e.g. rsync)

**Comment by jim618** [comment]
I have written a bash script that zips up everything in the var/brit/matcher/store directory that contains all the wallet id files and the BRIT addresses given out per day.

It is: create-brit-backup.sh in the top level of the BRIT server project

It produces a file e.g.
```
/var/brit/matcher/backup/backup-2015-06-01-17-48-42.zip
```

There is now a cron.daily job running on the hamburg server to produce these backups daily.

To do next is an rsync script that Jim / Gary can run from their machines to copy these files down to their machines to ensure there is a remote backup

**Comment by jim618** [comment]
I have pushed a script "rsync-brit-jim.sh" which rsyncs the hamburg BRIT backups to a local directory: /var/brit/hamburg

It's basically just an rsync and has the username 'jim' in it.
If @gary-rowe just wants to copy it and tweak the username etc it'll work.
It also expects an entry in ~/.ssh/config to the server - there's a comment in the script itself with an example.

This should get the job done for now.

Awaiting review and closing.

**Comment by jim618** [comment]
To remind myself to run the backup I have entered a line in my .bash_profile:

Recently run ? : /Users/jim/IdeaProjects/bitcoin-solutions/brit-server/rsync-brit-jim.sh

Then everytime I fire up a terminal I'll get a little reminder

**Comment by gary-rowe** [comment]
Just reviewed the script. It looks like it'll do the job on an ad hoc basis.

Closing.
